// Austin AI School — Events Data
// Shared across events.html and event-detail.html
const EVENTS = [
  // ─── WEEKLY TUESDAY WEBINARS (Free, Virtual, 7pm CT) ───
  {
    id: "opencall-launch-first-community-webinar",
    title: "OpenCall Launch — First Community Webinar",
    date: "2026-05-12T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "Join us for the inaugural Austin AI School community webinar. Meet founder Chris Lofton, learn what's coming, and connect with fellow AI enthusiasts.",
    fullDescription: "This is the one that starts it all. OpenCall Launch is Austin AI School's very first community webinar — a live, interactive session where founder Chris Lofton introduces the school's mission, upcoming programs, and the community we're building together. Whether you're a complete beginner curious about AI or a seasoned engineer looking for your next community, this is your invitation. We'll demo real AI tools, answer every question live, and lay out the roadmap for weekly webinars, workshops, and meetups through 2026.",
    agenda: [
      "Welcome & introductions (10 min)",
      "The Austin AI School story — why we exist (10 min)",
      "Live demo: Building an AI agent in real time (15 min)",
      "Upcoming events & programs roadmap (10 min)",
      "Open Q&A with Chris (15 min)"
    ],
    prerequisites: "None — this event is for everyone, from complete beginners to experienced engineers.",
    price: 0,
    spots: 500,
    registered: 147
  },
  {
    id: "ai-agents-101-what-they-are-why-they-matter",
    title: "AI Agents 101 — What They Are & Why They Matter",
    date: "2026-05-19T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "Demystify AI agents — what they are, how they work, and why every company will use them by 2027. No jargon, just clarity.",
    fullDescription: "AI agents are the biggest shift in software since the smartphone. But what actually are they? In this beginner-friendly webinar, Chris Lofton breaks down the anatomy of an AI agent — from LLM brains to tool use to memory systems. You'll see real examples of agents handling customer support, data analysis, and code generation. We'll cover the difference between chatbots and true agents, the major frameworks (LangChain, CrewAI, AutoGen), and why this technology is creating a massive wave of new jobs. Walk away understanding exactly what AI agents are and how to start building them.",
    agenda: [
      "What is an AI agent? Core concepts explained (15 min)",
      "Chatbots vs. agents — the critical difference (10 min)",
      "Live demo: Watch an AI agent complete a real task (10 min)",
      "The agent ecosystem: frameworks & tools (10 min)",
      "Q&A (15 min)"
    ],
    prerequisites: "None — perfect for beginners.",
    price: 0,
    spots: 500,
    registered: 89
  },
  {
    id: "from-zero-to-ai-engineer-career-change-roadmap",
    title: "From Zero to AI Engineer — Career Change Roadmap",
    date: "2026-05-26T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "A step-by-step roadmap for breaking into AI engineering — whether you're a teacher, marketer, or career changer with zero coding experience.",
    fullDescription: "You don't need a CS degree to become an AI engineer. In this webinar, Chris Lofton lays out the exact roadmap he's used to help hundreds of career changers land AI roles. We'll cover the skills that actually matter (hint: it's not PhD-level math), the fastest learning paths, how to build a portfolio that gets interviews, and the salary landscape for 2026. You'll hear real stories from Austin AI School graduates who went from non-technical backgrounds to $120K+ AI engineering roles. This is the honest, no-BS career guide you've been looking for.",
    agenda: [
      "The AI job market in 2026 — roles & salaries (10 min)",
      "Skills that matter vs. skills that don't (10 min)",
      "The 6-month career change roadmap (15 min)",
      "Building a portfolio that gets interviews (10 min)",
      "Success stories & Q&A (15 min)"
    ],
    prerequisites: "None — designed for career changers and beginners.",
    price: 0,
    spots: 500,
    registered: 112
  },
  {
    id: "live-build-rag-knowledge-base-45-minutes",
    title: "Live Build: RAG Knowledge Base in 45 Minutes",
    date: "2026-06-02T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "Watch Chris build a complete RAG (Retrieval-Augmented Generation) knowledge base from scratch — live, with real code, in under 45 minutes.",
    fullDescription: "RAG is the #1 most in-demand AI skill for 2026. In this live-coding webinar, Chris builds a complete Retrieval-Augmented Generation system from scratch. You'll watch him ingest documents, create embeddings, set up a vector database, and wire it all to an LLM — creating an AI that can answer questions about any set of documents. No slides, no theory — just real code running in real time. Follow along on your own machine or just watch and learn. By the end, you'll understand exactly how RAG works and have code you can use immediately.",
    agenda: [
      "What is RAG and why it matters (5 min)",
      "Setting up the environment (5 min)",
      "Document ingestion & chunking (10 min)",
      "Creating embeddings & vector store (10 min)",
      "Wiring the LLM & testing queries (15 min)",
      "Q&A and next steps (15 min)"
    ],
    prerequisites: "Basic Python knowledge helpful but not required. You can follow along or just watch.",
    price: 0,
    spots: 500,
    registered: 76
  },
  {
    id: "ai-in-the-enterprise-replacing-departments-with-agents",
    title: "AI in the Enterprise — Replacing Departments with Agents",
    date: "2026-06-09T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "How enterprises are using AI agents to automate entire departments — real case studies, ROI numbers, and implementation playbooks.",
    fullDescription: "The enterprise AI revolution isn't coming — it's here. Companies are deploying AI agents that handle customer support, process invoices, write reports, and manage HR workflows. In this webinar, Chris shares real case studies from his consulting work: how a 200-person company replaced its entire data entry team with AI agents, how a law firm cut research time by 80%, and how a marketing agency now produces 10x the content with the same team. You'll get concrete frameworks for identifying automation opportunities in your own organization and an honest assessment of what AI can and can't replace.",
    agenda: [
      "The state of enterprise AI in 2026 (10 min)",
      "Case study: Customer support automation (10 min)",
      "Case study: Back-office operations (10 min)",
      "Framework: Identifying AI opportunities (15 min)",
      "Q&A (15 min)"
    ],
    prerequisites: "None — particularly valuable for managers, directors, and business owners.",
    price: 0,
    spots: 500,
    registered: 63
  },
  {
    id: "prompt-engineering-masterclass",
    title: "Prompt Engineering Masterclass",
    date: "2026-06-16T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Dr. Sarah Chen",
    speakerBio: "AI Research Scientist and Prompt Engineering lead at a major tech company. Dr. Chen has published extensively on LLM optimization and teaches advanced prompt engineering techniques.",
    description: "Master the art and science of prompt engineering — advanced techniques that get dramatically better results from any LLM.",
    fullDescription: "Most people are using AI at 10% of its capability because they don't know how to prompt effectively. Guest speaker Dr. Sarah Chen shares the advanced prompt engineering techniques used by professional AI engineers — chain-of-thought reasoning, few-shot learning, system prompt architecture, and more. This isn't basic 'be specific' advice — these are the production-grade techniques that separate hobbyists from professionals. You'll learn frameworks for any use case: coding, writing, analysis, and creative work. Every technique is demonstrated live with before/after comparisons.",
    agenda: [
      "Why most prompts fail — common mistakes (10 min)",
      "Advanced techniques: CoT, few-shot, role-based (15 min)",
      "System prompt architecture for production (10 min)",
      "Live demo: Transforming bad prompts into great ones (15 min)",
      "Q&A (10 min)"
    ],
    prerequisites: "Basic experience using ChatGPT or similar LLMs.",
    price: 0,
    spots: 500,
    registered: 54
  },
  {
    id: "building-ai-chatbots-that-actually-work",
    title: "Building AI Chatbots That Actually Work",
    date: "2026-06-23T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "Learn to build AI chatbots that handle real conversations — with memory, context, tool use, and graceful error handling.",
    fullDescription: "Everyone's building chatbots. Most of them are terrible. In this webinar, Chris shows you how to build chatbots that actually work in production — handling edge cases, maintaining conversation context, using tools to take actions, and knowing when to escalate to humans. You'll see the architecture behind chatbots that handle 90%+ of customer conversations without human intervention. We'll cover the full stack: conversation design, memory management, API integrations, and deployment. Whether you're building for customer support, sales, or internal tools, you'll leave with a production-ready blueprint.",
    agenda: [
      "Why most chatbots fail (10 min)",
      "Conversation design principles (10 min)",
      "Building memory & context management (15 min)",
      "Tool use & API integrations (10 min)",
      "Deployment & monitoring — Q&A (15 min)"
    ],
    prerequisites: "Basic understanding of APIs. Some coding experience helpful.",
    price: 0,
    spots: 500,
    registered: 41
  },
  {
    id: "the-ai-stack-llms-embeddings-vector-dbs-explained",
    title: "The AI Stack — LLMs, Embeddings, Vector DBs Explained",
    date: "2026-06-30T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "A clear, visual explanation of every layer in the modern AI stack — from transformers to vector databases to orchestration frameworks.",
    fullDescription: "The modern AI stack can feel overwhelming — LLMs, embeddings, vector databases, RAG, fine-tuning, agents, orchestration. In this webinar, Chris breaks down every layer of the stack with clear explanations and visual diagrams. You'll understand how data flows from raw text through embeddings into vector databases, how LLMs generate responses, how RAG retrieves relevant context, and how agent frameworks tie it all together. This is the 'Aha!' session that makes everything else click. Perfect if you've been learning AI in pieces and need the big picture.",
    agenda: [
      "The AI stack overview — a visual map (10 min)",
      "LLMs: How transformers actually work (10 min)",
      "Embeddings & vector databases deep dive (15 min)",
      "RAG, agents & orchestration (10 min)",
      "Choosing your stack — Q&A (15 min)"
    ],
    prerequisites: "None — designed to be accessible to all levels.",
    price: 0,
    spots: 500,
    registered: 38
  },
  {
    id: "ai-for-non-technical-leaders",
    title: "AI for Non-Technical Leaders",
    date: "2026-07-07T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals in AI technologies and built AI systems for Fortune 500 companies.",
    description: "For executives, managers, and team leads — understand AI well enough to make strategic decisions without writing a line of code.",
    fullDescription: "You don't need to code to lead AI initiatives. In this session designed specifically for non-technical leaders, Chris covers everything you need to evaluate AI opportunities, manage AI teams, and make informed decisions about AI investments. We'll cover how to separate AI hype from reality, how to evaluate vendor claims, how to estimate ROI on AI projects, and how to build an AI-ready culture. You'll leave with a practical framework for leading AI adoption in your organization — no technical background required.",
    agenda: [
      "AI landscape for leaders — what's real, what's hype (10 min)",
      "Evaluating AI vendors & solutions (10 min)",
      "ROI frameworks for AI projects (15 min)",
      "Building an AI-ready team & culture (10 min)",
      "Q&A (15 min)"
    ],
    prerequisites: "None — specifically designed for non-technical professionals.",
    price: 0,
    spots: 500,
    registered: 29
  },
  {
    id: "multi-agent-systems-when-one-ai-isnt-enough",
    title: "Multi-Agent Systems — When One AI Isn't Enough",
    date: "2026-07-14T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Marcus Rivera",
    speakerBio: "Senior AI Engineer and multi-agent systems architect. Marcus has designed agent orchestration systems for enterprise clients handling millions of tasks daily.",
    description: "Explore multi-agent architectures where AI agents collaborate, delegate, and supervise each other to tackle complex problems.",
    fullDescription: "Single agents are powerful. Multiple agents working together are transformative. Guest speaker Marcus Rivera takes you into the world of multi-agent systems — where AI agents collaborate, delegate tasks, review each other's work, and tackle problems too complex for any single agent. You'll see real architectures: a research team of agents that writes better reports than humans, a coding swarm that builds and tests software, and an operations system that runs an entire business workflow. We'll cover CrewAI, AutoGen, and custom orchestration patterns. This is the cutting edge of AI engineering.",
    agenda: [
      "Why multi-agent? Limitations of single agents (10 min)",
      "Architecture patterns: hierarchy, democracy, swarm (15 min)",
      "Live demo: CrewAI multi-agent system (15 min)",
      "Production considerations & pitfalls (10 min)",
      "Q&A (10 min)"
    ],
    prerequisites: "Basic understanding of AI agents. Attending 'AI Agents 101' recommended.",
    price: 0,
    spots: 500,
    registered: 22
  },
  {
    id: "ai-ethics-responsible-deployment",
    title: "AI Ethics & Responsible Deployment",
    date: "2026-07-21T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Dr. Amara Johnson",
    speakerBio: "AI Ethics researcher and policy advisor. Dr. Johnson has consulted for government agencies and Fortune 100 companies on responsible AI deployment frameworks.",
    description: "Navigate the ethical landscape of AI — bias, privacy, transparency, and building AI systems that serve everyone fairly.",
    fullDescription: "Building AI is easy. Building AI responsibly is hard. Guest speaker Dr. Amara Johnson brings years of AI ethics research and policy work to this critical conversation. We'll cover real-world examples of AI bias, privacy violations, and unintended consequences — and more importantly, practical frameworks for preventing them. You'll learn about fairness metrics, transparency requirements, regulatory landscapes (EU AI Act, state laws), and how to build AI systems that are both powerful and responsible. Essential viewing for anyone deploying AI in production.",
    agenda: [
      "Real-world AI failures & what went wrong (10 min)",
      "Bias detection & mitigation strategies (15 min)",
      "Privacy, transparency & explainability (10 min)",
      "Regulatory landscape — what you must know (10 min)",
      "Building an ethics framework — Q&A (15 min)"
    ],
    prerequisites: "None — important for all AI practitioners and leaders.",
    price: 0,
    spots: 500,
    registered: 18
  },
  {
    id: "demo-day-community-project-showcase",
    title: "Demo Day — Community Project Showcase",
    date: "2026-07-28T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:30 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris hosts Demo Day and provides feedback on community projects.",
    description: "Community members demo the AI projects they've built. See what's possible, get inspired, and get feedback from Chris and the community.",
    fullDescription: "This is YOUR night. Demo Day is where Austin AI School community members showcase the AI projects they've been building. Whether it's a RAG system, an AI agent, a chatbot, or something we haven't seen before — this is your chance to present your work, get feedback, and inspire others. Chris Lofton hosts, providing constructive feedback and connecting builders with opportunities. Past Demo Days have led to job offers, co-founder matches, and open-source collaborations. Even if you're not presenting, come watch and see what your peers are building. It's the most inspiring night of the month.",
    agenda: [
      "Welcome & format overview (5 min)",
      "Project demos — 5 minutes each + Q&A (60 min)",
      "Community voting & feedback (10 min)",
      "Networking & open discussion (15 min)"
    ],
    prerequisites: "None to attend. To present, submit your project by July 25.",
    price: 0,
    spots: 500,
    registered: 34
  },
  {
    id: "ai-in-healthcare-finance-legal",
    title: "AI in Healthcare, Finance & Legal",
    date: "2026-08-04T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has implemented AI systems across healthcare, financial services, and legal industries.",
    description: "How AI is transforming three of the most regulated industries — with real case studies, compliance strategies, and career opportunities.",
    fullDescription: "Healthcare, finance, and legal are three of the highest-value, most-regulated industries being transformed by AI. In this webinar, Chris shares real implementations: AI systems that read medical imaging with 95%+ accuracy, financial models that detect fraud in real time, and legal AI that reviews contracts 100x faster than associates. But we also cover the hard parts — HIPAA compliance, financial regulations, attorney-client privilege, and how to build AI that satisfies regulators. If you work in or want to work in these industries, this session maps out exactly where AI is headed and where the opportunities are.",
    agenda: [
      "AI in Healthcare — diagnosis, admin, compliance (15 min)",
      "AI in Finance — trading, fraud, risk (10 min)",
      "AI in Legal — research, contracts, discovery (10 min)",
      "Navigating regulations & compliance (10 min)",
      "Career opportunities & Q&A (15 min)"
    ],
    prerequisites: "None — industry professionals and career changers welcome.",
    price: 0,
    spots: 500,
    registered: 15
  },
  {
    id: "fine-tuning-models-when-and-how",
    title: "Fine-Tuning Models — When & How",
    date: "2026-08-11T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has fine-tuned models for enterprise clients across multiple domains.",
    description: "Learn when fine-tuning makes sense (and when it doesn't), plus a live walkthrough of fine-tuning an open-source model.",
    fullDescription: "Fine-tuning is the most misunderstood tool in the AI engineer's toolkit. Most people who think they need fine-tuning actually need better prompts or RAG. In this webinar, Chris gives you the decision framework: when to use prompting, when to use RAG, and when fine-tuning is actually the right call. Then we'll do a live walkthrough of fine-tuning an open-source model using LoRA — from dataset preparation to training to evaluation. You'll see the real costs, timelines, and results. Stop guessing and start making informed decisions about fine-tuning.",
    agenda: [
      "Prompting vs. RAG vs. fine-tuning — decision framework (15 min)",
      "Dataset preparation for fine-tuning (10 min)",
      "Live walkthrough: Fine-tuning with LoRA (15 min)",
      "Evaluation & deployment (10 min)",
      "Q&A (10 min)"
    ],
    prerequisites: "Python basics. Understanding of LLMs helpful (attend 'The AI Stack' first).",
    price: 0,
    spots: 500,
    registered: 12
  },
  {
    id: "production-ai-monitoring-testing-deployment",
    title: "Production AI — Monitoring, Testing, Deployment",
    date: "2026-08-18T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has deployed production AI systems handling millions of requests for enterprise clients.",
    description: "The unglamorous but critical skills: testing AI systems, monitoring for drift, deploying safely, and handling failures gracefully.",
    fullDescription: "Building an AI demo is easy. Running AI in production is an entirely different game. In this webinar, Chris covers the skills that separate hobby projects from production systems: how to test AI outputs (it's not like testing regular software), how to monitor for quality drift, how to deploy with confidence using canary releases and A/B testing, and how to build fallback systems for when AI fails. These are the skills employers actually pay for — and they're rarely taught. If you want to be a professional AI engineer, not just a demo builder, this session is essential.",
    agenda: [
      "Why production AI is different (10 min)",
      "Testing strategies for non-deterministic systems (15 min)",
      "Monitoring, observability & drift detection (10 min)",
      "Deployment patterns: canary, blue-green, A/B (10 min)",
      "Q&A (15 min)"
    ],
    prerequisites: "Some software development experience. Understanding of basic AI concepts.",
    price: 0,
    spots: 500,
    registered: 8
  },
  {
    id: "building-your-ai-startup",
    title: "Building Your AI Startup",
    date: "2026-08-25T19:00:00-05:00",
    time: "7:00 PM CT",
    endTime: "8:00 PM CT",
    type: "webinar",
    format: "virtual",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and serial entrepreneur. Chris has built multiple tech companies and advises AI startups in the Austin ecosystem.",
    description: "From idea to MVP to first customers — a practical guide to building an AI startup in 2026, from someone who's done it.",
    fullDescription: "The AI startup opportunity is massive — but most people are building the wrong things. In this webinar, Chris shares hard-won lessons from building Austin AI School and advising AI startups. You'll learn how to identify AI startup ideas with real market demand, how to build an MVP in weeks (not months), how to find your first customers, and how to avoid the mistakes that kill 90% of AI startups. We'll cover funding strategies, technical architecture decisions, and the Austin AI ecosystem. Whether you have an idea or just the itch to start something, this session gives you the practical roadmap.",
    agenda: [
      "Finding AI startup ideas with real demand (10 min)",
      "Building an MVP fast — architecture decisions (15 min)",
      "Finding your first customers (10 min)",
      "Funding, team building & Austin ecosystem (10 min)",
      "Q&A (15 min)"
    ],
    prerequisites: "None — aspiring entrepreneurs at all levels welcome.",
    price: 0,
    spots: 500,
    registered: 10
  },

  // ─── MONTHLY SATURDAY WORKSHOPS (Paid $199, In-Person, 10am–4pm) ───
  {
    id: "hands-on-ai-agent-building-workshop",
    title: "Hands-On AI Agent Building Workshop",
    date: "2026-06-14T10:00:00-05:00",
    time: "10:00 AM CT",
    endTime: "4:00 PM CT",
    type: "workshop",
    format: "in-person",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has trained 10,000+ professionals and built production AI agent systems for Fortune 500 companies.",
    description: "A full-day, hands-on workshop where you build 3 production-ready AI agents from scratch. Laptops required. Lunch included.",
    fullDescription: "This is not a lecture. This is a full-day, hands-on building session where you walk in with a laptop and walk out with 3 working AI agents. Chris Lofton guides you through building a customer support agent, a research agent, and a multi-tool agent — all production-ready, all yours to keep and customize. You'll use Python, LangChain, and OpenAI APIs in a structured, step-by-step format with Chris available for 1-on-1 help. Limited to 30 seats to ensure everyone gets personal attention. Lunch, snacks, and coffee provided. Held at our Austin training center.",
    agenda: [
      "Setup & environment configuration (30 min)",
      "Agent fundamentals — architecture walkthrough (30 min)",
      "Build #1: Customer support agent with memory (90 min)",
      "Lunch break & networking (60 min)",
      "Build #2: Research agent with web search & summarization (90 min)",
      "Build #3: Multi-tool agent with API integrations (60 min)",
      "Deployment & next steps (30 min)"
    ],
    prerequisites: "Python basics required. Bring a laptop with Python 3.10+ installed. We'll send setup instructions before the event.",
    price: 199,
    spots: 30,
    registered: 18
  },
  {
    id: "rag-systems-knowledge-bases-deep-dive",
    title: "RAG Systems & Knowledge Bases Deep Dive",
    date: "2026-07-12T10:00:00-05:00",
    time: "10:00 AM CT",
    endTime: "4:00 PM CT",
    type: "workshop",
    format: "in-person",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and former enterprise AI consultant. Chris has built RAG systems processing millions of documents for enterprise clients.",
    description: "Build a production-grade RAG system from scratch in this full-day workshop. Covers advanced chunking, hybrid search, evaluation, and deployment.",
    fullDescription: "RAG (Retrieval-Augmented Generation) is the most in-demand AI skill of 2026. In this full-day workshop, you'll build a complete, production-grade RAG system that goes far beyond basic tutorials. Chris Lofton walks you through advanced document processing, intelligent chunking strategies, hybrid search (semantic + keyword), re-ranking, evaluation frameworks, and deployment patterns. You'll work with real enterprise documents and build a system you can adapt for any use case — internal knowledge bases, customer support, legal research, or medical documentation. Limited to 30 seats. Lunch included.",
    agenda: [
      "RAG architecture deep dive (30 min)",
      "Document processing & advanced chunking (45 min)",
      "Embeddings, vector stores & hybrid search (45 min)",
      "Lunch break & networking (60 min)",
      "Re-ranking & response generation (45 min)",
      "Evaluation frameworks — measuring quality (45 min)",
      "Production deployment & scaling (30 min)",
      "Wrap-up & next steps (30 min)"
    ],
    prerequisites: "Python required. Basic understanding of LLMs (attend any of our webinars first). Bring a laptop with Python 3.10+.",
    price: 199,
    spots: 30,
    registered: 11
  },
  {
    id: "ai-for-business-leaders-strategy-workshop",
    title: "AI for Business Leaders — Strategy Workshop",
    date: "2026-08-09T10:00:00-05:00",
    time: "10:00 AM CT",
    endTime: "4:00 PM CT",
    type: "workshop",
    format: "in-person",
    speaker: "Chris Lofton",
    speakerBio: "Founder of Austin AI School and enterprise AI strategy consultant. Chris has developed AI strategies for organizations ranging from startups to Fortune 500 companies.",
    description: "A non-technical strategy workshop for executives and business leaders. Build your organization's AI roadmap in one day. No coding required.",
    fullDescription: "This workshop is designed exclusively for business leaders who need to understand AI strategically — not technically. In one intensive day, Chris Lofton guides you through building a complete AI strategy for your organization. You'll assess your AI readiness, identify high-impact automation opportunities, evaluate build-vs-buy decisions, create an implementation timeline, and develop a change management plan. No coding, no jargon — just practical strategy work with a room full of fellow leaders. You'll leave with a written AI roadmap customized to your organization. Limited to 30 seats. Lunch included.",
    agenda: [
      "AI landscape briefing for leaders (30 min)",
      "Exercise: AI readiness assessment for your org (45 min)",
      "Identifying high-impact AI opportunities (45 min)",
      "Lunch & executive networking (60 min)",
      "Build vs. buy — vendor evaluation framework (45 min)",
      "Building your AI roadmap (45 min)",
      "Change management & team building (30 min)",
      "Presentations & feedback (30 min)"
    ],
    prerequisites: "None — this is a non-technical workshop. Designed for executives, directors, VPs, and business owners.",
    price: 199,
    spots: 30,
    registered: 7
  },

  // ─── QUARTERLY MEETUPS (Free, In-Person, Austin TX) ───
  {
    id: "austin-ai-meetup-networking-lightning-talks",
    title: "Austin AI Meetup — Networking & Lightning Talks",
    date: "2026-06-28T18:00:00-05:00",
    time: "6:00 PM CT",
    endTime: "9:00 PM CT",
    type: "meetup",
    format: "in-person",
    speaker: "Chris Lofton & Community Speakers",
    speakerBio: "Chris Lofton hosts with 5-minute lightning talks from community members working on AI projects in Austin.",
    description: "Connect with Austin's AI community. Lightning talks, networking, food & drinks. Free and open to everyone.",
    fullDescription: "The Austin AI Meetup is the city's premier gathering for AI practitioners, enthusiasts, and curious minds. Join us for an evening of lightning talks (5 minutes each — fast, focused, inspiring), open networking, and great conversation. Whether you're a senior ML engineer or just starting your AI journey, you'll find your people here. Past meetups have led to job connections, co-founder matches, and lifelong friendships. Chris Lofton kicks things off with a community update, then we hear from 6-8 community speakers on topics ranging from cutting-edge research to weekend AI projects. Food, drinks, and good vibes provided.",
    agenda: [
      "Doors open — food & networking (30 min)",
      "Welcome & community updates — Chris Lofton (10 min)",
      "Lightning talks — 6-8 speakers, 5 min each (50 min)",
      "Open networking & conversations (90 min)"
    ],
    prerequisites: "None — all levels welcome. Just bring yourself and curiosity.",
    price: 0,
    spots: 100,
    registered: 42
  },
  {
    id: "austin-ai-meetup-fall-edition",
    title: "Austin AI Meetup — Fall Edition",
    date: "2026-09-27T18:00:00-05:00",
    time: "6:00 PM CT",
    endTime: "9:00 PM CT",
    type: "meetup",
    format: "in-person",
    speaker: "Chris Lofton & Community Speakers",
    speakerBio: "Chris Lofton hosts with lightning talks from community members and special guests from the Austin AI ecosystem.",
    description: "Fall edition of Austin's favorite AI meetup. Lightning talks, demos, networking, and a look ahead at Q4 programs.",
    fullDescription: "The Fall Edition of the Austin AI Meetup brings the community back together as the summer wraps up. This edition features lightning talks from community members, live demos of projects built over the summer, and a preview of Austin AI School's Q4 programs. Special guests from Austin's AI startup scene will share what they're building and hiring for. It's the perfect event to reconnect, meet new people, and get energized for the fall learning season. As always — free, open to everyone, with food and drinks provided.",
    agenda: [
      "Doors open — food & networking (30 min)",
      "Welcome & summer recap — Chris Lofton (10 min)",
      "Lightning talks & live demos (50 min)",
      "Q4 preview & what's next (10 min)",
      "Open networking (90 min)"
    ],
    prerequisites: "None — all levels welcome.",
    price: 0,
    spots: 100,
    registered: 14
  }
];
